spring.application.name: entry-level-java-challenge

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.challenge.api: INFO
    org.springframework.security: DEBUG